### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by svagi** [Azure/azurefile-dockervolumedriver#2]
Hello, I have followed the readme and I got the following error:

```
svagi@api:~$ git clone https://github.com/Azure/azurefile-dockervolumedriver src/azurefile
Cloning into 'src/azurefile'...
remote: Counting objects: 140, done.
remote: Total 140 (delta 0), reused 0 (delta 0), pack-reused 140
Receiving objects: 100% (140/140), 77.21 KiB | 0 bytes/s, done.
Resolving deltas: 100% (27/27), done.
Checking connectivity... done.
svagi@api:~$ export GOPATH=`pwd`
svagi@api:~$ export GO15VENDOREXPERIMENT=1
svagi@api:~$ cd src/azurefile
svagi@api:~/src/azurefile$ go build -o azurefile
driver.go:11:2: cannot find package "github.com/Azure/azure-sdk-for-go/storage" in any of:
    /usr/src/pkg/github.com/Azure/azure-sdk-for-go/storage (from $GOROOT)
    /home/svagi/src/github.com/Azure/azure-sdk-for-go/storage (from $GOPATH)
driver.go:12:2: cannot find package "github.com/Sirupsen/logrus" in any of:
    /usr/src/pkg/github.com/Sirupsen/logrus (from $GOROOT)
    /home/svagi/src/github.com/Sirupsen/logrus (from $GOPATH)
driver.go:13:2: cannot find package "github.com/ahmetalpbalkan/dkvolume" in any of:
    /usr/src/pkg/github.com/ahmetalpbalkan/dkvolume (from $GOROOT)
    /home/svagi/src/github.com/ahmetalpbalkan/dkvolume (from $GOPATH)
main.go:8:2: cannot find package "github.com/codegangsta/cli" in any of:
    /usr/src/pkg/github.com/codegangsta/cli (from $GOROOT)
    /home/svagi/src/github.com/codegangsta/cli (from $GOPATH)
```

**Comment by ahmetb** [comment]
Oh I guess you need to run "go get" first

**Comment by ahmetb** [comment]
Hmm no this project uses godep. Can you please check your Go version is at least 1.5?

**Comment by svagi** [comment]
@ahmetalpbalkan Yes, you need to run `go get` first. Maybe it's a good idea to mention it in README. Thx.

**Comment by ahmetb** [comment]
Not really I was wrong. You should not be running go get. Can you please check your go version?

**Comment by svagi** [comment]
@ahmetalpbalkan After I installed all the dependencies with `go get`, everything works as expected.

```
$ go version
go version xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux/amd64
```

**Comment by ahmetb** [comment]
Your go version seems a bit weird. There's no go 4.9.1. All the dependencies are already in the source code and if you use go1.5 it should automatically find these without go get.

**Comment by svagi** [comment]
@ahmetalpbalkan Ok, thank you. 

Btw I also have problem to use postgres with `/var/lib/postgresql/data` volume. Do you know if this is considered a bad practice?

**Comment by ahmetb** [comment]
Yeah you probably shouldn't use this other than a few files you'll read and write occasionally. Databases are a bit more critical to be stored in file service I think. Please take a look at this article: https://web.archive.org/web/20150427210728/https://msdn.microsoft.com/en-us/library/azure/dn790517.aspx

**Comment by svagi** [comment]
Ok, thank you!
