### ISSUE TITLE
Cannot specify 'share' option from DCOS Marathon

### ISSUE THREAD

**Issue by kobelb** [Azure/azurefile-dockervolumedriver#34]
I'm using DCOS on Azure to manage my docker containers, which is running the following docker command:

`docker run -i -t --volume my_volume:/data --volume-driver azurefile busybox`

However, when doing so, the following error is output:  _docker: Error response from daemon: create my_volume: VolumeDriver.Create: missing volume option: 'share'._

 I'm trying to figure out the best way to provide the 'share' without having to run a separate `docker volume create` on all of my nodes, and they won't let me use the `-v $(docker volume create --name my_volume - share=my_volume):/data` syntax in the DCOS marathon app templates.

**Comment by ahmetb** [comment]
cc:@anhowe @rgardler any ideas or pointers on how people use this plugin on DCOS?

**Comment by ahmetb** [comment]
@kobelb I'm not sure how DCOS deals with docker volumes but quite a lot of volume plugins require extra options. If DCOS is not providing this option, that is probably a feature request for them. I also noticed the `-o` is missing in your command above, could that be your issue?

**Comment by ahmetb** [comment]
@kobelb Do you have a satisfactory answer for this issue? Did you have a chance to take this up to DCOS? Not having a feature to specify volume driver options does not sound right.

**Comment by kobelb** [comment]
@ahmetalpbalkan I sincerely appreciate you looking into this, and I apologize for not replying earlier.

I found a place the DCOS documentation that specifies that it's up to the cluster administrator to create the volumes on all of the nodes prior to utilizing the Volume Driver. I do agree that this isn't the most ideal situation, and I'll suggest this feature to them.

**Comment by ahmetb** [comment]
@kobelb thanks! Closing on our end here.
