### ISSUE TITLE
creating azure client: illegal base64 data at input byte 8 

### ISSUE THREAD

**Issue by bertvannuffelen** [Azure/azurefile-dockervolumedriver#36]
Dear,

I get both on the 2.0, 2.1 release and the direct build on a ubuntu 16.04 the message

FATA[0000] error creating azure client: illegal base64 data at input byte 8 

What does this mean?

kr,

Bert

**Comment by bertvannuffelen** [comment]
hi,

it seems it means invalid/incorrect credentials.

kr,

Bert

**Comment by ahmetb** [comment]
Yes it looks like your storage key is malformed.

**Comment by bertvannuffelen** [comment]
thanks for the confirmation, but maybe this can be reported in a more human readable error message?

**Comment by ahmetb** [comment]
@bertvannuffelen you are right. I opened an issue at https://github.com/Azure/azure-sdk-for-go/issues/344 to track this.

**Comment by buckett** [comment]
Just got this as well, would be nice to have a better error:

```
FATA[0000] error creating azure client: illegal base64 data at input byte 84 
```

although nice colour in your logs.

**Comment by buckett** [comment]
Ok this was a UI problem with the azure portal for me, double clicking (then copy/paste) showed the whole of the box highlighed, but it was actually only highlighting up to the first non alphanumeric.

**Comment by buckett** [comment]
I think you need to update you're vendor drop of azure to get the fix in this project as I'm still seeing it on 0.5.1

**Comment by ahmetb** [comment]
@buckett opened #71 to track this.
