### ISSUE TITLE
Azure German Support

### ISSUE THREAD

**Issue by reschrei1** [Azure/azurefile-dockervolumedriver#41]
How can I configure storage path url's that link to azure german cloud resources (core.cloudapi.de)?

**Comment by ahmetb** [comment]
@reschrei1 hi, that is not possible today. I am adding this to our backload as a feature request. Thanks for reporting and sorry for the inconvenience.

**Comment by ahmetb** [comment]
@reschrei1 I have a patch at https://github.com/Azure/azurefile-dockervolumedriver/pull/43, do you mind compiling and giving it a try? Compiling a new binary is rather very simple: `GOOS=linux go build` will give you a binary that will work on Linux if you have a Go compiler installed. Let me know if you need help.

**Comment by reschrei1** [comment]
Thx for fast fixing, looks fine!
I had some trouble compiling source with older Go version (1.2.x). After upgrade to 1.6 I compiled without error.

Some annotations:
Please change the following code sections in driver.go:
cmd := exec.Command("mount", "-t", "cifs", fmt.Sprintf("//%s.file.%s/%s", **storageBase, accountName**, shareName), mountpoint, "-o", fmt.Sprintf("vers=3.0,username=%s,password=%s,dir_mode=0777,file_mode=0777", accountName, accountKey), "--verbose")
    out, err := cmd.CombinedOutput()
    if err != nil {
        return fmt.Errorf("mount failed: %v\noutput=%q", err, out)

-->

cmd := exec.Command("mount", "-t", "cifs", fmt.Sprintf("//%s.file.%s/%s", **accountName, storageBase**, shareName), mountpoint, "-o", fmt.Sprintf("vers=3.0,username=%s,password=%s,dir_mode=0777,file_mode=0777", accountName, accountKey), "--verbose")
    out, err := cmd.CombinedOutput()
    if err != nil {
        return fmt.Errorf("mount failed: %v\noutput=%q", err, out)

further add to .conf script
 **export AZURE_STORAGE_BASE="$AZURE_STORAGE_BASE"**

at the end of line

**Comment by ahmetb** [comment]
Thanks @reschrei1, sorry for delay on fixing this. It totally slipped from my mind. I have taken the fixes you mentioned at #43, merged it and released it as v0.4.0 that you can grab here:  https://github.com/Azure/azurefile-dockervolumedriver/releases/tag/0.4.0 Please let us know if you encounter any issues.
