### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [Azure/azurefile-dockervolumedriver#42]
Hello,

Some of our users are running Mac instead of ubuntu. Can they use it ? 

Thanks

**Comment by ahmetb** [comment]
Hello, this is not really a dev tool. Also this process has to be running in the same virtual machine Docker engine is running on. I don't think Docker for Mac lets you do that for now. If it lets you install plugins and if Mac supports CIFS mounts then it could work, but that is not a use case we support yet.
