### ISSUE TITLE
Error when creating docker volume

### ISSUE THREAD

**Issue by mildlyill** [Azure/azurefile-dockervolumedriver#49]
Hello,

I'd like to test out the azure driver with rancher, however I am getting the following error after following the setup instructions.

```
docker volume create -d azurefile --name docker -o share=docker
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Error response from daemon: create docker: VolumeDriver.Create: error creating azure file share: storage: service returned error: StatusCode=403, ErrorCode=AuthenticationFailed, ErrorMessage=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:a5e77a67-001a-00c0-12f0-ed4629000000
Time:2016-08-04T01:32:22.1578801Z, RequestId=a5e77a67-001a-00c0-12f0-ed4629000000, QueryParameterName=, QueryParameterValue=
```

I can see the service seems to be running fine, but there is an error:

`systemctl status azurefile-dockervolumedriver
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
● azurefile-dockervolumedriver.service - Azure File Service Docker Volume Driver
   Loaded: loaded (/etc/systemd/system/azurefile-dockervolumedriver.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2016-08-04 01:15:38 UTC; 22min ago
     Docs: https://github.com/Azure/azurefile-dockervolumedriver/
 Main PID: 21249 (azurefile-docke)
    Tasks: 5
   Memory: 6.3M
      CPU: 113ms
   CGroup: /system.slice/azurefile-dockervolumedriver.service
           └─21249 /usr/bin/azurefile-dockervolumedriver`

I've tried changing the storage key, same error.

I'm running the standard Xenial image, not sure if there is anything else I would need to do.

**Comment by ahmetb** [comment]
@mildlyill  It indeed looks like an issue with your storage credentials. How does your `/etc/default/azurefile-dockervolumedriver` file look like?

Alternatively you can stop the service (`systemctl stop azurefile-dockervolumedriver`) and invoke the driver directly (see `azurefile-dockervolumedriver --help`)  with your credentials. Please try that and keep the process running while you try to create a volume and see if it succeeds.

**Comment by mildlyill** [comment]
Thanks for the quick response. I ended up re-installing everything and it is now working,. Sorry for jumping the gun with this!
