### ISSUE TITLE
Free inodes not reported correctly / always zero

### ISSUE THREAD

**Issue by gjonespf** [Azure/azurefile-dockervolumedriver#51]
First of all, congrats on an awesome piece of kit! Is very useful already.

I'm trying to get a volume using this storage driver working using a tool called [Minio](https://github.com/minio/minio) so that I can circumvent the limitations using AzureFS on Linux (no SMB3 support, poor tooling around syncing full directories of files in Linux).  However, the free inodes reported by this driver are always zero, which causes issues in Minio (reports no free space).

Example would be similar to this (doctored):

> $ docker volume create --name my_volume -d azurefile -o share=myshare
> $ docker run -i -t -v my_volume:/data busybox
> $ df -h /data
> $ Filesystem                                                   Size  Used Avail Use% Mounted on
> $ //example.file.core.windows.net/myshare   10G   36M   10G   1% /data
> $ df -i /data
> $ Filesystem                                                  Inodes IUsed IFree IUse% Mounted on
> $ //example.file.core.windows.net/myshare      0     0     0     - /data

Is this perhaps an issue with the underlying CIFS driver, or perhaps even Unix support on the Azure FS SMB shares?  I'd imagine this will cause issues with other software checking the free inodes also.

FYI - similar issue on Minio:
[minio server fails to start over CephFS storage directory](https://github.com/minio/minio/issues/2425)

**Comment by ahmetb** [comment]
@gjonespf Glad you found this plugin useful!

It appears like this might be a SMB protocol or CIFS driver issue. I highly doubt this falls is caused by the docker plugin. Can you please try mounting the Azure File Storage share manually yourself? Instructions are here: https://azure.microsoft.com/en-us/documentation/articles/storage-how-to-use-files-linux/

**Comment by gjonespf** [comment]
Hey @ahmetalpbalkan , yup can definitely confirm same issues (zero available inodes) mounting using instructions on that web page.  I should have thought of trying that.  So either an issue in the CIFS kernel driver/user drivers or perhaps Azure FS mounts not supporting the Unix extensions.  Either way, I'll have to try things another way, which is a shame.
Thanks for the prompt response!
Is there any way I can log an issue for the Azure File guys to look into this?

**Comment by ahmetb** [comment]
@gjonespf please feel free to raise this issue in the comments section on the link above. I'm sure the Storage folks on Azure side would be interested.
