### ISSUE TITLE
 0.4.1: not a recognized volume driver option: "remotepath"

### ISSUE THREAD

**Issue by denisyfrolov** [Azure/azurefile-dockervolumedriver#53]
Seems like "remotepath" option doesn't work on latest release (0.4.1):

```
user@host:~$ sudo docker volume create --name volume_name -d azurefile \
-o share=volume_name \
-o uid=33 \
-o gid=33 \
-o filemode=0644 \
-o dirmode=0755 \
-o nolock=true \
-o remotepath=public_html
Error response from daemon: create volume_name: VolumeDriver.Create: error validating metadata: not a recognized volume driver option: "remotepath"

```

**Comment by ahmetb** [comment]
@denisyfrolov that sounds odd. @zlatan any ideas? you've been using this, right?

**Comment by denisyfrolov** [comment]
@ahmetalpbalkan yep, I not see the problem in source code too, but I used the binary from here https://github.com/Azure/azurefile-dockervolumedriver/releases/download/0.4.1/azurefile-dockervolumedriver so maybe problem exactly in the current build?

**Comment by ahmetb** [comment]
@denisyfrolov have you upgraded from an older version? I feel like an old version of the `azurefile-dockervolumedriver` server would say that.

**Comment by denisyfrolov** [comment]
@ahmetalpbalkan nope, it was fresh installed VM with Debian 8 from the Azure library

**Comment by ahmetb** [comment]
@denisyfrolov thanks I will try to reproduce this and circle back here.

**Comment by denisyfrolov** [comment]
@ahmetalpbalkan the problem definitely affect only binary, I build 0.4.1 from the source and remotepath option works fine

**Comment by ahmetb** [comment]
@denisyfrolov /facepalm. I just realized we did not actually release a version with the latest changes in `master`. 0.4.1 does not contain the remotepath change. I will work on releasing a version today.

**Comment by denisyfrolov** [comment]
@ahmetalpbalkan that explains a lot  :-) sorry.. my bad, I didn't checked the commits list

**Comment by ahmetb** [comment]
You can download v0.5.0. https://github.com/Azure/azurefile-dockervolumedriver/releases/tag/v0.5.0
