### ISSUE TITLE
Incorrect version number in the "azurefile-dockervolumedriver -v" output

### ISSUE THREAD

**Issue by denisyfrolov** [Azure/azurefile-dockervolumedriver#54]
On latest release (0.4.1):

```
user@host:~$ /usr/bin/azurefile-dockervolumedriver -v          
azurefile-dockervolumedriver version 0.2.1
```

Incorrect version number in **main.go** on line **21**:

`cmd.Version = "0.2.1"`

**Comment by ahmetb** [comment]
@denisyfrolov thanks for noticing. Apparently they went out of sync. I’ll fix.
