### ISSUE TITLE
"quota size" option

### ISSUE THREAD

**Issue by denisyfrolov** [Azure/azurefile-dockervolumedriver#55]
Need the "quota size" option to change default value 5TB of quota per file share.

**Comment by ahmetb** [comment]
Hi @denisyfrolov, I'm started to become a bit skeptical about this as I start looking more into this. It [appears like](https://msdn.microsoft.com/en-us/library/azure/dn167008.aspx) 5TB is the max quota for a share, so I am assuming you are trying to create smaller shares.

Problem is, volume driver options are all stuff that actually get used every time a share is mounted (e.g. `share name`, `uid`, `gid`). If we create a `quota` option here that is used _only_ when a File Share is being created, that will easily lead to confusion when it is not used when a File Share with given name already exists.

I can easily imagine users providing different `quota` values when they run `docker volume create` on different machines and at different times, and only the first one is going to be used. So it kind of becomes like a piece of data that you have keep track and pass the same value everywhere to keep it all consistent and in sync.

I think this volume plugin is the wrong place to solve this problem. Assuming you're not dealing with 1000s of File Shares, my suggestion would be pre-creating a File Share using Azure API/CLI with the custom quota size, and then using it here in this plugin.

Having an option flag which is only used but gets passed over and over again sounds a bit anti-pattern for a declarative approach. Therefore I am not in favor of implementing this feature, at least for now. Does this make sense?

**Comment by msftgits** [comment]
This driver is no longer supported and will not be maintained moving forward. We recommend users use CloudStor for Docker native solutions.

Thanks for your contribution, but to reduce confusion, we are closing issues, pull requests, and marking the repo as 'Archive' for the time being.
