### ISSUE TITLE
Service does not start on VM reboot

### ISSUE THREAD

**Issue by mildlyill** [Azure/azurefile-dockervolumedriver#61]
Hi there.

Things are working as expected with the driver.

One issue I'm finding is that when I reboot the host, the volume driver service does not start.

I find it stopped, and I have to start it manually.

Once I issue the start command, all is well.

Any ideas?

**Comment by ahmetb** [comment]
Is your machine using systemd or upstart?

**Comment by mildlyill** [comment]
systemd... Ubuntu 16.04

**Comment by ahmetb** [comment]
What is the output of "systemctl status <unit>"?

**Comment by mildlyill** [comment]
The whole status, or just for azurefile-dockervolumedriver?

Here's the output of the above, let me know if you'd like the full status as it's over 300 lines:

azurefile-dockervolumedriver.service
   Loaded: loaded (/etc/systemd/system/azurefile-dockervolumedriver.service; bad; vendor preset: enabled)
   Active: active (running) since Thu 2016-09-08 17:37:39 UTC; 22h ago
 Main PID: 5958 (azurefile-docke)
    Tasks: 5
   Memory: 3.9M
      CPU: 1.175s
   CGroup: /system.slice/azurefile-dockervolumedriver.service
           └─5958 /usr/bin/azurefile-dockervolumedriver

Sep 09 03:31:35 RANCHER01 azurefile-dockervolumedriver[5958]: time="2016-09-09T03:31:35Z" level=error msg="could not fetch metadata: cannot read metadata: open /etc/docker/plugins/azurefile/volumes/f304e85d
Sep 09 04:06:52 RANCHER01 azurefile-dockervolumedriver[5958]: time="2016-09-09T04:06:52Z" level=error msg="could not fetch metadata: cannot read metadata: open /etc/docker/plugins/azurefile/volumes/49cfa0a1
Sep 09 04:11:31 RANCHER01 azurefile-dockervolumedriver[5958]: time="2016-09-09T04:11:31Z" level=error msg="could not fetch metadata: cannot read metadata: open /etc/docker/plugins/azurefile/volumes/25a25fc7
Sep 09 04:31:24 RANCHER01 azurefile-dockervolumedriver[5958]: time="2016-09-09T04:31:24Z" level=error msg="could not fetch metadata: cannot read metadata: open /etc/docker/plugins/azurefile/volumes/178fdbb0
Sep 09 04:40:34 RANCHER01 azurefile-dockervolumedriver[5958]: time="2016-09-09T04:40:34Z" level=error msg="could not fetch metadata: cannot read metadata: open /etc/docker/plugins/azurefile/volumes/49cfa0a1
Sep 09 04:41:01 RANCHER01 azurefile-dockervolumedriver[5958]: time="2016-09-09T04:41:01Z" level=error msg="could not fetch metadata: cannot read metadata: open /etc/docker/plugins/azurefile/volumes/49cfa0a1
Sep 09 05:04:57 RANCHER01 azurefile-dockervolumedriver[5958]: time="2016-09-09T05:04:57Z" level=error msg="could not fetch metadata: cannot read metadata: open /etc/docker/plugins/azurefile/volumes/azfs_wp:
Sep 09 05:04:57 RANCHER01 azurefile-dockervolumedriver[5958]: time="2016-09-09T05:04:57Z" level=error msg="error creating azure file share: storage: service returned error: StatusCode=400, ErrorCode=Invalid
Sep 09 05:05:17 RANCHER01 azurefile-dockervolumedriver[5958]: time="2016-09-09T05:05:17Z" level=error msg="could not fetch metadata: cannot read metadata: open /etc/docker/plugins/azurefile/volumes/azfs-wp:
Sep 09 05:05:17 RANCHER01 azurefile-dockervolumedriver[5958]: time="2016-09-09T05:05:17Z" level=info msg="created azure file share \"azfs-wp\"" name=azfs-wp operation=create options=map[share:azfs-wp]

**Comment by ahmetb** [comment]
Hmm it looks enabled. I'm assuming you did "systemctl enable azurefile-dockervolumedriver" while installing, which should be making this start on every boot. 

Can you please reboot and run the status command again?

**Comment by mildlyill** [comment]
Sure here you go. I pretty much followed your steps to the letter, so not sure why it doesn't start up on boot:

● azurefile-dockervolumedriver.service
   Loaded: loaded (/etc/systemd/system/azurefile-dockervolumedriver.service; bad; vendor preset: enabled)
   Active: inactive (dead)

Sep 09 17:36:21 RANCHER01 systemd[1]: [/etc/systemd/system/azurefile-dockervolumedriver.service:1] Assignment outside of section. Ignoring.
Sep 09 17:36:21 RANCHER01 systemd[1]: [/etc/systemd/system/azurefile-dockervolumedriver.service:2] Assignment outside of section. Ignoring.
Sep 09 17:36:21 RANCHER01 systemd[1]: [/etc/systemd/system/azurefile-dockervolumedriver.service:3] Assignment outside of section. Ignoring.
Sep 09 17:36:21 RANCHER01 systemd[1]: [/etc/systemd/system/azurefile-dockervolumedriver.service:4] Assignment outside of section. Ignoring.
Sep 09 17:36:21 RANCHER01 systemd[1]: [/etc/systemd/system/azurefile-dockervolumedriver.service:5] Assignment outside of section. Ignoring.
Sep 09 17:36:21 RANCHER01 systemd[1]: [/etc/systemd/system/azurefile-dockervolumedriver.service:6] Assignment outside of section. Ignoring.

**Comment by ahmetb** [comment]
@mildlyill looks like your `/etc/systemd/system/azurefile-dockervolumedriver.service` is broken, do you mind providing the contents? Have you edited this file manually?

**Comment by mildlyill** [comment]
You're absolutely right, when I took a look it was somehow missing the opening [ for some reason!

Thanks for the help!

Unit]
Description=Azure File Service Docker Volume Driver
Documentation=https://github.com/Azure/azurefile-dockervolumedriver/
Requires=docker.service
After=nfs-utils.service
Before=docker.service

[Service]
EnvironmentFile=/etc/default/azurefile-dockervolumedriver
ExecStart=/usr/bin/azurefile-dockervolumedriver $AF_OPTS
Restart=always
StandardOutput=syslog

[Install]
WantedBy=multi-user.target
