### ISSUE TITLE
Windows Container Support

### ISSUE THREAD

**Issue by knom** [Azure/azurefile-dockervolumedriver#67]
Support for running on-top of Windows would be great!

**Comment by BarnumD** [comment]
Yes!  There seems to be no way, currently, to access an SMB share from a Windows container.  I'm hoping that this volume driver, although made for azure, would also work for that purpose.

**Comment by lurock** [comment]
I would like to see support for Windows server containers too.

**Comment by msftgits** [comment]
This driver is no longer supported and will not be maintained moving forward. We recommend users use CloudStor for Docker native solutions.

Thanks for your contribution, but to reduce confusion, we are closing issues, pull requests, and marking the repo as 'Archive' for the time being.
