### ISSUE TITLE
Update vendored azure-sdk-for-go

### ISSUE THREAD

**Issue by ahmetb** [Azure/azurefile-dockervolumedriver#71]
So that we get the fix for https://github.com/Azure/azure-sdk-for-go/issues/344

ref: #36.

**Comment by msftgits** [comment]
This driver is no longer supported and will not be maintained moving forward. We recommend users use CloudStor for Docker native solutions.

Thanks for your contribution, but to reduce confusion, we are closing issues, pull requests, and marking the repo as 'Archive' for the time being.
