### ISSUE TITLE
Docker container cannot start due to permission errors?

### ISSUE THREAD

**Issue by ropstah** [Azure/azurefile-dockervolumedriver#72]
We're trying to use the Azure driver to externalize our volumes for Docker in order to run MongoDB. I've setup the azurefile-dockervolumedriver and created two volumes. This created the shares in our Azure Storage account.

However when I try to run a MongoDB container it shuts down again immediately with the following errors for which I have no idea on how to solve it as I followed all procedures:

```
kernel: aufs au_opts_verify:1597:dockerd[1594]: dirperm1 breaks the protection by the permission bits on the lower branch
kernel: aufs au_opts_verify:1597:dockerd[3695]: dirperm1 breaks the protection by the permission bits on the lower branch
systemd-udevd[37637]: Could not generate persistent MAC address for vethf345bd2: No such file or directory
kernel: device veth97a0c1e entered promiscuous mode
kernel: IPv6: ADDRCONF(NETDEV_UP): veth97a0c1e: link is not ready
systemd-udevd[37638]: Could not generate persistent MAC address for veth97a0c1e: No such file or directory
kernel: eth0: renamed from vethf345bd2
kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth97a0c1e: link becomes ready
kernel: docker0: port 1(veth97a0c1e) entered forwarding state
kernel: docker0: port 1(veth97a0c1e) entered forwarding state
kernel: docker0: port 1(veth97a0c1e) entered disabled state
kernel: vethf345bd2: renamed from eth0
kernel: docker0: port 1(veth97a0c1e) entered disabled state
kernel: device veth97a0c1e left promiscuous mode
kernel: docker0: port 1(veth97a0c1e) entered disabled state
```

Any suggestions would be greatly appreciated.

**Comment by ahmetb** [comment]
@ropstah have you tried using it with a regular volume? Where are the `kernel:` logs coming from, where do you see these logs?

**Comment by ahmetb** [comment]
@ropstah please consider closing if you are no longer seeking an answer.

**Comment by ropstah** [comment]
@ahmetalpbalkan you are right. I found the problem is not related to the driver but to MongoDb in conjunction with Docker.
