### ISSUE TITLE
azurefile-dockervolumedriver for DC/OS json

### ISSUE THREAD

**Issue by TamasSzerb** [Azure/azurefile-dockervolumedriver#74]
Hello,

Could you please point out how could I use this azurefile-dockervolumedriver driveer for DC/OS application JSON? I cannot find any resource for this - yet.

Thanks,

Tamas

**Comment by ahmetb** [comment]
@TamasSzerb I suggest reading DCOS documentation on how to configure Docker Volume Plugins. This is just another plugin really.

**Comment by ahmetb** [comment]
@TamasSzerb  There is an example here: https://mesosphere.github.io/marathon/docs/external-volumes.html I suggest following that tutorial. It should work the same way once your Mesos agent nodes are configured with `azurefile-dockervolumedriver` in advance.
