### ISSUE TITLE
"azurefile plugin not found" on Swarm, ACS/Azure

### ISSUE THREAD

**Issue by tommed** [Azure/azurefile-dockervolumedriver#75]
I have docker swarm running in an Azure Container Service. I thought whilst running in Azure it would be awesome to make use of Azure File Storage to storage shared volumes, so I ran:

`docker volume create --name teststorage3 -d azurefile -o share=teststorage3share`

However, it fails instantly with the following error:

`Error response from daemon: create teststorage3: create teststorage3: Error looking up volume plugin azurefile: plugin not found`

docker info:
Filters: health, port, dependency, affinity, constraint
Nodes: 1
 swarm-agent-32EE87A9000001: 10.0.0.5:2375
  └ Status: Healthy
  └ Containers: 10
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 702 MiB
  └ Labels: executiondriver=, kernelversion=3.19.0-65-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-11-10T08:23:52Z
Plugins:
 Volume:
 Network:
Swarm:
 NodeID:
 Is Manager: false
 Node Address:
Security Options:
Kernel Version: 3.19.0-65-generic
Operating System: linux
Architecture: amd64
CPUs: 1
Total Memory: 702 MiB
Name: 42dd1279654d
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
WARNING: No kernel memory limit support

docker version:
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      swarm/1.1.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   a0fd82b
 Built:        Thu Feb  4 08:55:18 UTC 2016
 OS/Arch:      linux/amd64

**Comment by ahmetb** [comment]
@tommed have you installed the driver on all nodes?

**Comment by tommed** [comment]
Ah ha! Apologies, problem was that I didn't RTM!

For future reference, Clicking one of the install Ubuntu links provided the installation steps to get this working.

Will try tomorrow and update accordingly if necessary.

Thank you
