### ISSUE TITLE
Passing options to docker service create --mount (docker swarm mode)

### ISSUE THREAD

**Issue by one1zero1one** [Azure/azurefile-dockervolumedriver#77]
Hello, I have multiple volumes created from the same share (using different -o remotepath for each volume) - and I'm trying to mount them in multiple services. However I need different uid and gid for each mount, within the containers.

I'm trying to pass volume-opt like this in the service create (as per [docu](https://github.com/docker/docker/blob/master/docs/reference/commandline/service_create.md#add-bind-mounts-or-volumes)):

`-mount=type=volume,volume-driver=azurefile,volume-opt=uid=104,volume-opt=gid=107,source=grafana01-data,destination=/var/lib/grafana/db`

However - inside the container, the mount comes out without any of the options specified, e.g 

`rw,relatime,vers=3.0,sec=ntlmssp,cache=strict,username=XXX,domain=X,uid=0,forceuid,gid=0,forcegid,addr=XXX,file_mode=0777,dir_mode=0777,persistenthandles,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,actimeo=1`

Is this behaviour expected or a limitation? Thanks.

**Comment by ahmetb** [comment]
@one1zero1one you said "inside the container", that's a bit  confusing. You're not really supposed to see any mounts inside the container. Can you please show the output of `mount` command on the Linux host?

The expectation is the uid/gid you specify for the volume will be specified on the host. Inside the container, you need to have a user/group with that uid/gid as well and start your container with a specific user (`docker run --uid=N ...`).

**Comment by one1zero1one** [comment]
@ahmetalpbalkan thanks, I figured it out. I'm dealing with docker 1.12.3 swarm -  volumes are mounted on all nodes of the swarm, with _docker volume_ create, specifying different -o uid -o gid and -o remotepath. With _docker service_ create, I --mount the volumes with volume-driver=azurefile without any need for additional options.  My use case that has the same share for all the volumes got me confused, sorry for that.
