### ISSUE TITLE
docker volume ls hangs

### ISSUE THREAD

**Issue by djeeg** [Azure/azurefile-dockervolumedriver#79]
Hi, wondering if anyone has seen a problem like this

After a while my swarm node become unstable, think I have traced it back to a problem with azure volume driver

Try this

```
sudo docker volume ls
^C
```

Doesnt return, must break out of it

```
docker --version
Docker version 1.13.0-rc4, build 88862e7
```

https://github.com/Azure/azurefile-dockervolumedriver/releases/download/v0.5.1/azurefile-dockervolumedriver

Checked a few other posts, my settings looks normal

systemctl status

```
 ¦ +-azurefile-dockervolumedriver.service?[m
 ¦ ¦ +-860 /usr/bin/azurefile-dockervolumedriver?[m
```
 
systemctl status azurefile-dockervolumedriver

```
?[0;1;32m??[0m azurefile-dockervolumedriver.service - Azure File Service Docker Volume Driver?[m
   Loaded: loaded (/etc/systemd/system/azurefile-dockervolumedriver.service; ena?[m
   Active: ?[0;1;32mactive (running)?[0m since Sat 2016-12-31 12:04:59 UTC; 27min ago?[m
     Docs: https://github.com/Azure/azurefile-dockervolumedriver/?[m
 Main PID: 860 (azurefile-docke)?[m
    Tasks: 5?[m
   Memory: 7.2M?[m
      CPU: 64ms?[m
   CGroup: /system.slice/azurefile-dockervolumedriver.service?[m
           +-860 /usr/bin/azurefile-dockervolumedriver?[m
?[m
Dec 31 12:04:59 dockernode1 systemd[1]: Started Azure File Service Docker?[m
```

journalctl -fu azurefile-dockervolumedriver

```
-- Logs begin at Sat 2016-12-31 12:04:56 UTC. --
Dec 31 12:04:59 dockernode1 systemd[1]: Started Azure File Service Docker Volume Driver.
```

cat /etc/systemd/system/azurefile-dockervolumedriver.servicenode

```
[Unit]
Description=Azure File Service Docker Volume Driver
Documentation=https://github.com/Azure/azurefile-dockervolumedriver/
Requires=docker.service
After=nfs-utils.service
Before=docker.service

[Service]
EnvironmentFile=/etc/default/azurefile-dockervolumedriver
ExecStart=/usr/bin/azurefile-dockervolumedriver $AF_OPTS
Restart=always
StandardOutput=syslog

[Install]
WantedBy=multi-user.target
```
Remove the volumes manually

```
sudo docker volume rm volrethinkdb
volrethinkdb
sudo docker volume rm volredis
volredis
```

Still cant list volumes

```
sudo docker volume ls
^C
```

Then restart docker and driver

```
sudo systemctl restart azurefile-dockervolume
sudo systemctl restart docker.service
```

I can now list local volumes again

```
sudo docker volume ls

DRIVER              VOLUME NAME
local               14b613555464ce57****
local               16e08822291d2a547*****
```

**Comment by libby2cm** [comment]
@djeeg we ran into this issue as well, so we had to abandon containerizing anything that needed persistent storage unfortunately.  It appeared to be an issue where after a certain period of idle time, the smb connection would go stale/timeout, which the driver doesn't handle well, and results in the behavior you are seeing.  Hopefully someone picks this up and irons it out, as it would open a ton of use cases for us.

**Comment by petrux** [comment]
It happens to me as well but without docker stuff, just mounting my File Storage into my linux VM. Any news on the issue?

**Comment by msftgits** [comment]
This driver is no longer supported and will not be maintained moving forward. We recommend users use CloudStor for Docker native solutions.

Thanks for your contribution, but to reduce confusion, we are closing issues, pull requests, and marking the repo as 'Archive' for the time being.
