### ISSUE TITLE
Unable to find listenbuffer

### ISSUE THREAD

**Issue by withinboredom** [Azure/azurefile-dockervolumedriver#8]
I get this error trying to build:

``` bash
robert@cloud-base:~/src/azurefile$ go get
package github.com/Azure/azure-sdk-for-go/storage
        imports github.com/Sirupsen/logrus
        imports github.com/ahmetalpbalkan/dkvolume
        imports github.com/docker/docker/pkg/listenbuffer
        imports github.com/docker/docker/pkg/listenbuffer
        imports github.com/docker/docker/pkg/listenbuffer: cannot find package "github.com/docker/docker/pkg/listenbuffer" in any of:
        /usr/lib/go/src/pkg/github.com/docker/docker/pkg/listenbuffer (from $GOROOT)
        /home/robert/src/github.com/docker/docker/pkg/listenbuffer (from $GOPATH)
```

**Comment by ahmetb** [comment]
@withinboredom you're not supposed to do `go get` in this project. Please read “Building” section in the README.  https://github.com/Azure/azurefile-dockervolumedriver#building We use godep to vendor dependencies.

**Comment by withinboredom** [comment]
Sorry, I had seen #2

**Comment by withinboredom** [comment]
Also, for anyone who stumbles upon this issue: upgrade go (ubuntu 14.04 comes with pretty old go)

**Comment by ahmetb** [comment]
@withinboredom more accurately, don't ever install golang package in ubuntu, follow instructions at https://golang.org/doc/install#install to install Go on your system.

**Comment by withinboredom** [comment]
yep, learned my lesson
