### ISSUE TITLE
Docker Swarm cluster not recognizing plugin after install on all nodes

### ISSUE THREAD

**Issue by ehanlon** [Azure/azurefile-dockervolumedriver#81]
### Configuration
- 5 nodes 
- Docker 1.13
- Ubuntu 16.04.1 LTS
- Swarm mode enabled on all nodes
- v0.5.1 of azurfile driver installed

### Repro
1. Deploy nodes using `docker-machine create -d azure`
2. `docker-machine ssh` to each VM to install the volume driver
3. `systemctl status azurefile-dockervolumedriver` shows that the service started successfully and is active.
4. Run `docker stack deploy -c docker-compose.yml <service_name>` on swarm manager node
5. `docker stack ps <service_name>` shows current state of all containers as **Pending**
6. `docker inspect <container_id>` in the service shows state as pending due to "no suitable node missing plugin"
7. Running `docker info` on the nodes shows:

    ```
    Plugins:
      Volume: local
    ```

### Workaround
1. After completing the installation of the plugin, create a test volume by running `docker volume create -d azurefile -o share=<my_test_share>`
2. Running `docker info` on the node now yields:

    ```
     Plugins:
       Volume: local azurefile
    ```

### Expected behavior
Install plugin on nodes, and Docker recognizes that the plugin is already installed without running `docker volume create -d azurefile -o share=<my_test_share>` to toggle recognition.

**Comment by alexsandro-xpt** [comment]
Why you do not use Docker for Azure? It's have cloudstor plugin.

**Comment by ehanlon** [comment]
@alexsandro-xpt we're using this in an environment that is behind an ExpressRoute, and has policies that prevent us from creating resources with Public IP's.

The other issue is that my team uses Stable Channel, and according to the [documentation for CloudStor](https://docs.docker.com/docker-for-azure/persistent-data-volumes/#use-cloudstor) it is currently only available on the Edge Channel.

>**Note:** Cloudstor is currently only pre-installed and pre-configured in the edge channel distribution of Docker for Azure v17.03.

**Comment by alexsandro-xpt** [comment]
Alright @ehanlon, I'm using CloudStor, my only question about CloudStor is about backups. All time when we create a new cluster using Docker for Azure, it's don't request us nothing about using an exist NFS for reaprovetation.

This my question. No answer yet.

**Comment by msftgits** [comment]
This driver is no longer supported and will not be maintained moving forward. We recommend users use CloudStor for Docker native solutions.

Thanks for your contribution, but to reduce confusion, we are closing issues, pull requests, and marking the repo as 'Archive' for the time being.
