### ISSUE TITLE
Support installation as a Docker plugin

### ISSUE THREAD

**Issue by markvr** [Azure/azurefile-dockervolumedriver#82]
Hi, are there any plans to update this so it can be installed as a plugin with `docker plugin install`?

It would make it much easier to use!

**Comment by markvr** [comment]
....bounce.....anyone?

Has development on this been abandoned?  There seems to have been nothing for ~8months now and docker has moved on in that time.  This could be really useful, but what state of support is it in from Microsoft?

**Comment by gjonespf** [comment]
@markvr see #78 this is same request.

**Comment by msftgits** [comment]
This driver is no longer supported and will not be maintained moving forward. We recommend users use CloudStor for Docker native solutions.

Thanks for your contribution, but to reduce confusion, we are closing issues, pull requests, and marking the repo as 'Archive' for the time being.
