### ISSUE TITLE
Files with colon in name don't work

### ISSUE THREAD

**Issue by saikatguha** [Azure/azurefile-dockervolumedriver#84]
## Steps ##
1. Mount an azurefile volume and cd into it
2. `touch AA:BB`

## Actual Results ##
No such file or directory

## Expected Results ##
File is created.

**Comment by msftgits** [comment]
This driver is no longer supported and will not be maintained moving forward. We recommend users use CloudStor for Docker native solutions.

Thanks for your contribution, but to reduce confusion, we are closing issues, pull requests, and marking the repo as 'Archive' for the time being.
