### ISSUE TITLE
Cannot run command docker-machine create -d azure ...

### ISSUE THREAD

**Issue by joshlester** [Azure/azurefile-dockervolumedriver#86]
Hi 
Im running:
OS: macOS Sierra (10.12.3)
DOCKER: Version 17.03.1-ce-mac5 (16048)

When running the command:
_docker-machine create -d azure --azure-open-port 80 --azure-resource-group rendivo rendivo-compositor_

I receive the following error:
_Running pre-create checks...
(rendivo-compositor) Completed machine pre-create checks.
Creating machine...
(rendivo-compositor) Querying existing resource group.  name="rendivo"
(rendivo-compositor) Creating resource group.  name="rendivo" location="australiasoutheast"
(rendivo-compositor) Configuring availability set.  name="docker-machine"
(rendivo-compositor) Configuring network security group.  name="rendivo-compositor-firewall" location="australiasoutheast"
(rendivo-compositor) Querying if virtual network already exists.  name="docker-machine-vnet" rg="rendivo" location="australiasoutheast"
(rendivo-compositor) Creating virtual network.  rg="rendivo" location="australiasoutheast" name="docker-machine-vnet"
(rendivo-compositor) Configuring subnet.  name="docker-machine" vnet="docker-machine-vnet" cidr="192.168.0.0/16"
(rendivo-compositor) Creating public IP address.  name="rendivo-compositor-ip" static=false
(rendivo-compositor) Creating network interface.  name="rendivo-compositor-nic"
(rendivo-compositor) Creating storage account.  name="vhdsp1yu5om8mjek5t3jh20w" location="australiasoutheast" sku=Standard_LRS
(rendivo-compositor) Creating virtual machine.  name="rendivo-compositor" location="australiasoutheast" size="Standard_A1_v2" username="docker-user" osImage="canonical:UbuntuServer:16.04.0-LTS:latest"
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Error creating machine: Error running provisioning: error installing docker:_

The issue seems to be affecting my existing setup as well. 

When I run the command:
 _eval $(docker-machine env host-comp-rendivo)_

I receive error:
_Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "13.73.197.96:2376": dial tcp 13.73.197.96:2376: getsockopt: connection refused
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers._

When I run the command:
_docker-machine regenerate-certs host-comp-rendivo_

I receive error:
Error getting SSH command to check if the daemon is up: ssh command error:
command : sudo docker version
err     : exit status 1
output  : Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.5.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
time="2017-04-07T06:39:56Z" level=fatal msg="Cannot connect to the Docker daemon. Is 'docker -d' running on this host?"

I've tried restarting the docker service running inside the virtual machine (_host-comp-rendivo_) by running:
_sudo systemctl restart azurefile-dockervolume_

I also tried restarting the virtual machine itself.

Any help is greatly appreciated.

Thanks,
Josh.

**Comment by carcer** [comment]
I am also having this issue.  This my output:

> Running pre-create checks...
> (hailto-development) Completed machine pre-create checks.
> Creating machine...
> (hailto-development) Querying existing resource group.  name="hailto2"
> (hailto-development) Creating resource group.  name="hailto2" location="westus"
> (hailto-development) Configuring availability set.  name="hailto-development"
> (hailto-development) Configuring network security group.  name="hailto-development-firewall" location="westus"
> (hailto-development) Querying if virtual network already exists.  name="hailto-development" rg="hailto2" location="westus"
> (hailto-development) Creating virtual network.  name="hailto-development" rg="hailto2" location="westus"
> (hailto-development) Configuring subnet.  cidr="192.168.0.0/16" name="docker-machine" vnet="hailto-development"
> (hailto-development) Creating public IP address.  name="hailto-development-ip" static=false
> (hailto-development) Creating network interface.  name="hailto-development-nic"
> (hailto-development) Creating storage account.  name="vhdsz2hboz92zw6katb1o1v8" location="westus" sku=Standard_LRS
> (hailto-development) Creating virtual machine.  username="docker-user" osImage="canonical:UbuntuServer:16.04.0-LTS:16.04.201608150" name="hailto-development" location="westus" size="Standard_A2"
> Waiting for machine to be running, this may take a few minutes...
> Detecting operating system of created instance...
> Waiting for SSH to be available...
> Detecting the provisioner...
> Provisioning with ubuntu(systemd)...
> Installing Docker...
> Copying certs to the local machine directory...
> Copying certs to the remote machine...
> Setting Docker configuration on the remote daemon...
> Error creating machine: Error running provisioning: ssh command error:
> command : sudo systemctl -f start docker
> err     : exit status 1
> output  : Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

Running `systemctl status docker.service` results in;

> docker.service - Docker Application Container Engine
>    Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
>   Drop-In: /etc/systemd/system/docker.service.d
>            └─10-machine.conf
>    Active: inactive (dead) (Result: exit-code) since Tue 2017-08-29 13:42:59 UTC; 7min ago
>      Docs: https://docs.docker.com
>   Process: 7804 ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscac
>  Main PID: 7804 (code=exited, status=1/FAILURE)
> 
> Aug 29 13:42:59 hailto-development systemd[1]: docker.service: Unit entered failed state.
> Aug 29 13:42:59 hailto-development systemd[1]: docker.service: Failed with result 'exit-code'.
> Aug 29 13:42:59 hailto-development systemd[1]: docker.service: Service hold-off time over, scheduling restart.
> Aug 29 13:42:59 hailto-development systemd[1]: Stopped Docker Application Container Engine.
> Aug 29 13:42:59 hailto-development systemd[1]: docker.service: Start request repeated too quickly.
> Aug 29 13:42:59 hailto-development systemd[1]: Failed to start Docker Application Container Engine.

**Comment by msftgits** [comment]
This driver is no longer supported and will not be maintained moving forward. We recommend users use CloudStor for Docker native solutions.

Thanks for your contribution, but to reduce confusion, we are closing issues, pull requests, and marking the repo as 'Archive' for the time being.
