### ISSUE TITLE
remotepath does not create directory if it doesn't exist

### ISSUE THREAD

**Issue by saikatguha** [Azure/azurefile-dockervolumedriver#87]
Having to manually create `remotepath=` directories in the share significantly complicates CI/CD pipelines. Given azurefile already creates non-existent shares, not creating directories make for inconsistent behavior.

**Comment by msftgits** [comment]
This driver is no longer supported and will not be maintained moving forward. We recommend users use CloudStor for Docker native solutions.

Thanks for your contribution, but to reduce confusion, we are closing issues, pull requests, and marking the repo as 'Archive' for the time being.
