### ISSUE TITLE
Why not support Azure Blob based volume driver?

### ISSUE THREAD

**Issue by mingaliu** [Azure/azurefile-dockervolumedriver#89]

**Comment by alexsandro-xpt** [comment]
May because Blob is not a virtual disc with file system engine, like File type.

I guess, to really use Blob, should have a mediator. with that emulate a file system engine and so, use it at Linux or Windows OS.

**Comment by jmaitrehenry** [comment]
If you want to use a Page blob and attach it as a disk, you may check for http://github.com/thecodeteam/rexray

**Comment by msftgits** [comment]
This driver is no longer supported and will not be maintained moving forward. We recommend users use CloudStor for Docker native solutions.

Thanks for your contribution, but to reduce confusion, we are closing issues, pull requests, and marking the repo as 'Archive' for the time being.
