### ISSUE TITLE
Enabling "Secure transfer required" on an Azure Storage account stops the driver working

### ISSUE THREAD

**Issue by samattridge** [Azure/azurefile-dockervolumedriver#90]
If you enable the "Secure transfer required" option on an Azure Storage Account you get the following error: 

> docker: Error response from daemon: error while mounting volume '/var/run/docker/volumedriver/azurefile/myvol': VolumeDriver.Mount: mount failed: exit status 32
output="mount.cifs kernel mount options: ip=x.x.x.x,unc=\\\\somestorageaccount.file.core.windows.net\\ssl,vers=3.0,file_mode=0777,dir_mode=0777,uid=0,gid=0,user=somestorageaccount,pass=********\nmount error(13): Permission denied\nRefer to the mount.cifs(8) manual page (e.g. man mount.cifs)\n".

After disabling the option, it begins to work again.  I've checked the code for the driver and can see that it is using useHTTPS when talking to the storage client so not entirely sure why this causes it to break.

I'm using v0.5.1 of the driver.

Hope this helps.

**Comment by msftgits** [comment]
This driver is no longer supported and will not be maintained moving forward. We recommend users use CloudStor for Docker native solutions.

Thanks for your contribution, but to reduce confusion, we are closing issues, pull requests, and marking the repo as 'Archive' for the time being.
