### ISSUE TITLE
for web app on linux?

### ISSUE THREAD

**Issue by TamasSzerb** [Azure/azurefile-dockervolumedriver#91]
Hello,

How this can be used for Web App On Linux?

Tamas

**Comment by ThiemeNL** [comment]
Hi @TamasSzerb did you manage to use this in Web App for Containers on Linux? I'm stuck on the same question.

**Comment by ThiemeNL** [comment]
Hi @TamasSzerb the Azure web app doesn't support this: https://docs.microsoft.com/en-us/azure/app-service/containers/app-service-linux-faq (We do not currently support bringing your own storage.)

BUT and this is really great! You can use WEBSITES_ENABLE_APP_SERVICE_STORAGE which will share the /home directory across the instances and will be persisted. The web app is using azure storage in the background.

**Comment by msftgits** [comment]
This driver is no longer supported and will not be maintained moving forward. We recommend users use CloudStor for Docker native solutions.

Thanks for your contribution, but to reduce confusion, we are closing issues, pull requests, and marking the repo as 'Archive' for the time being.
