### ISSUE TITLE
azurefile-dockervolumedriver configuration ignored

### ISSUE THREAD

**Issue by ayayalar** [Azure/azurefile-dockervolumedriver#94]
Hello Ahmet,

When I create a docker volume, the volume gets created in the storage attached to the Azure VM instead of the storage specified in the configuration.  Any suggestions what I might be doing wrong?

Thank you,

Arif

**Comment by jmaitrehenry** [comment]
Hi @ayayalar 

Do you have a step to reproduce? Like command line instruction?

**Comment by msftgits** [comment]
This driver is no longer supported and will not be maintained moving forward. We recommend users use CloudStor for Docker native solutions.

Thanks for your contribution, but to reduce confusion, we are closing issues, pull requests, and marking the repo as 'Archive' for the time being.
