### ISSUE TITLE
Clone repo from Github

### ISSUE THREAD

**Issue by PradeepJaiswar** [Azure/azurefile-dockervolumedriver#96]
I want to dynamically create containers for each student of batch and each student should have it's own copy of Github repo in the container. Also, the student should be able to keep their code changes for future. Even when container stops next time he should be able to mount his previously cloned repo into the new container.

Is there any way to cloning the repo from Github while creating volume? 

I am sure this is possible but don't know how.

**Comment by jmaitrehenry** [comment]
@PradeepJaiswar No, it's not possible with this plugin, but your container could have an entrypoint that check if the repo exists and clone it.

**Comment by msftgits** [comment]
This driver is no longer supported and will not be maintained moving forward. We recommend users use CloudStor for Docker native solutions.

Thanks for your contribution, but to reduce confusion, we are closing issues, pull requests, and marking the repo as 'Archive' for the time being.
